// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFS_FileProcessor
{
    public partial class Application
    {
        public Application()
        {
            PropertyApplication = new HashSet<PropertyApplication>();
        }

        public int ApplicationID { get; set; }
        public string Application1 { get; set; }
        public string Description { get; set; }
        public int? ParentID { get; set; }
        public int? Position { get; set; }
        public int? ModuleID { get; set; }
        public byte[] Image { get; set; }
        public string Namespace { get; set; }
        public string SingularName { get; set; }
        public string Assembly { get; set; }
        public int? ApplicationTypeID { get; set; }
        public string DocumentationLocation { get; set; }
        public string SourceCodeLocation { get; set; }
        public int? ApplicationStatusID { get; set; }
        public bool? IgnorePermissions { get; set; }

        public virtual ICollection<PropertyApplication> PropertyApplication { get; set; }
    }
}