// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFS_FileProcessor
{
    public partial class Property
    {
        public Property()
        {
            PropertyApplication = new HashSet<PropertyApplication>();
        }

        public int PropertyID { get; set; }
        public string Property1 { get; set; }
        public int? PropertyTypeID { get; set; }

        public virtual ICollection<PropertyApplication> PropertyApplication { get; set; }
    }
}